name: Update Packages DX

on:
  schedule:
    - cron: "0 0 * * 0" # This will run the action every Sunday at midnight
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  update-packages:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create a new branch
        run: git checkout -b create-pull-request/patch

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Check for outdated packages
        run: |
          npm outdated || true
          npx npm-check-updates "/@new-objects/" -u

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_TOKEN }}
          title: "Update outdated packages"
          body: "This PR updates outdated packages of @new-objects/*."
